### ISSUE TITLE
Flyttbar tegnforklaring

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#100]
Det er ønskelig at tegnforklaringsboksen er enten flyttbar på skjermen (helst), og/eller har mulighet til autonom breddejustering. Noen tegnforklaringstekster er så lange, at det knapt er plass til mer enn én klasse, men når man justerer bredden, utvider jo også temakart-boksen  og tar opp mye av kartvinduet. En flyttbar tegnforklaringsboks vil også gi større muligheter for brukerstyrt kart-design.

**Comment by emoen** [comment]
Update: https://www.sencha.com/forum/showthread.php?308987-draggable-and-resizeable&p=1128511#post1128511

**Comment by emoen** [comment]
Se på dette i en ny versjon av kartklienten

**Comment by emoen** [comment]
Jeg har ikke fått til drag&drop i den versjonen extjs som geoexplorer bruker. Jeg foreslår at vi ser på denne funksjonaliteten i en ny versjon av kartklienten.
