### ISSUE TITLE
4. Admindatabasen: De grønne paneler fungerer ikke i IE

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#123]
De grønne paneler i admindatamasen (Framside, Hovedtema, Kartbilder, Kartlag, Karttjenester) fungerer ikke i IE.

**Comment by PAH1** [comment]
![mareano_admin](https://cloud.githubusercontent.com/assets/5708044/11369325/98850bbc-92be-11e5-8681-bedcd18bcf8b.JPG)
Move layer virker ikke.

**Comment by aangerman** [comment]
La inn piler i størrelsen 16x16 og i  png-format på test-server.

**Comment by aangerman** [comment]
La inn piler i størrelsen 16x16 og i png-format på test-server.
