### ISSUE TITLE
"Save" tekst for kartlag fører til en tom /kartlags/view

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#124]
'Edit kartlag' http://appl1.imr.no/mareano_admin/kartlag_nos/edit/[nnn]. Etter å ha fylt tekstbokser og trykket på "Save" hopper applikasjonen videre til en tom /kartlags/view- side. Den burde gå tilbake til det aktuelle kartlaget-view for at man kunne fortsette med utforming av det samme kartlaget. Slikt fungerte det i gammel database og det var det mest logiske og praktiske. Men nå må man begynne å lete etter kartlaget på nytt i admindatabasen isteden.

**Comment by aavelepland** [comment]
Best hvis  "Save [kartlag]" førte tilbake til det aktuelle laget slik at man kunne jobbe videre med det til det er ferdig. Dvs.
Save==> _http://www.mareano.no/mareano_admin/kartlags/view/[#det aktuelle laget]_
(og IKKE Save==> _http://www.mareano.no/mareano_admin/kartlags/index_)

**Comment by aangerman** [comment]
Nytt og endret kartlag fører tilbake til kartlags/view/nnn
Nytt eller endret kartlag_nos eller -ens gjør det samme.
