### ISSUE TITLE
1. Editering i Admin-databasen

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#135]
Når man editerer i en karttjeneste, kartbilde, kartlag, legend, og lagrer - er det mest praktisk at man går automatisk tilbake til den karttjenesten/-bildet/-laget. Som editering fungerer nå, må man etter lagring begynne å lete objektet på nytt helt fra framsiden igjen. Det tar mye tid og er meningsløst.  Dette er fint ordnet i gammel database, så det må gå an i den nye.

**Comment by aangerman** [comment]
Hei, jeg er helt enig. Her er det ganske mange sider det gjelder, så jeg tester, endrer og noter her hvordan det virker etter endringene:

Edit på toppnivåene kartbilde, kartlag og karttjenester fører til view'et av det som er opprettet

I kartlags/view/[nn] blir man returnert til samme side hvis man oppretter eller endrer
- Norsk Tekst
- Engelsk Tekst
- Legends
- Spesialpunkt

I karttjenestes/view/[nn] blir man returnert til samme side hvis man oppretter eller endrer
- Norsk Tekst
- Engelsk Tekst

I kartbildes/view/[nn] blir man returnert til samme side hvis man oppretter eller endrer
- Norsk Tekst
- Engelsk Tekst

Mvh,
Andreas
