### ISSUE TITLE
3. Legg til ny legend - nedtrekksmeny unødvendig

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#136]
Når man vil legge til tegnforklaring til et kartlag, havner man på en side 'Add legend' med nedtrekksmeny, der Rutenett står default. Denne valgmuligheten er unødvendig og i virkeligheten til mye bry, for da må man begynne å lete etter det aktuelle laget i den lange uoversiktige lista. Når man jobber med et kartlag, er dette laget valgt alt, og dette valget skal gjelde også den nye legenden. 
Når jeg er på kartlagsiden 'Korntsørrelse', f.eks. og klikker på 'New legend', så betyr det at legenden skal gjelde Kornstørrelse, ikke Rutenett. Og når jeg lagrer ny legend, vil jeg gå tilbake til Kornstørrelse, ikke få opp en tom side med tekst "Legend has been saved".
![undvendig_nedtrekksmeny](https://cloud.githubusercontent.com/assets/5802537/3102831/eb8cbe56-e64c-11e3-98e9-2ccaac15e277.PNG)

**Comment by aangerman** [comment]
fjernet nedtrekksmeny og returnerer brukeren til kartlaget ved lagring

**Comment by aangerman** [comment]
fjernet nedtrekksmeny og returnerer brukeren til kartlaget ved lagring
