### ISSUE TITLE
Verktøyknapper Zoom og Panorer slår seg ikke av

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#140]
Verktøyknapper 'Zoom ved å tegne en firkant' og 'Panorer kart' i Mareano kartapplikasjon slår seg ikke av når man velger andre verktøy. Det er problematisk ved bruk av verktøyene 'Identifiser' (get feature info) og 'Mål', da klikk på kartet medfører også uønsket zoom eller panorering. 
Alle verktøy burde være aktivert alene, og slås av når neste verktøy blir valgt.

**Comment by emoen** [comment]
Funksjonalitet fra de to verktøysgruppene kan brukes samtidig.
