### ISSUE TITLE
Zoom til kartlagets utstrekning vs. Zoom to make scale-dependent layer visible

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#142]
'Zoom til kartlagets utstrekning' vs. 'Zoom to make scale-dependent layer visible':
De to funksjonene kan ikke bruke samme BBOX-koords fra Admindatabasen. Noen lag har mye større utstrekning enn at de kan vises helt innenfor sine målestokksgrenser. 
'Zoom to make scale-dependent layer visible' kan kanskje kobles til Scalemin og Scalemax isteden.

**Comment by emoen** [comment]
'zoom til zoom-avhengig kartlagsutstrekning' bruker maxScale: https://github.com/Norwegian-marine-datacentre/mareano/blob/master/src/main/webapp/javascript/mareanoComposer.js#L176

og 'zoom til maks utstrekning' bruker den maksimale utstrekningen (https://github.com/emoen/gxp/blob/master/src/script/plugins/ZoomToExtent.js#L103)  av alle kartlagene - som vanligvis er utstrekningen til bakgrunnskartet: https://github.com/emoen/gxp/blob/master/src/script/plugins/ZoomToExtent.js#L26 -
