### ISSUE TITLE
1 Lagre kart-funksjon tillater og forserer overskriving av lagrede kart

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#143]
Ved bruk av lenke til et på forhånd lagret kart (f.eks. ...kart/mareano.html#maps/145) er det mulig å forandre kartet og så lagre på nytt med samme kartnummer. Dette gjør at alle brukere kan endre lenker som skal vise til bestemte kart, f.eks. fra forsiden eller fra tematekster. 
Samtidig er det ikke mulig å forandre kartnummer til kartet man vil lagre, slik at man faktisk er nødt til å ødelegge et annet kart hvis man vil gjøre egne forandringer på et på forhånd lagret kart og lagre dem til senere.

**Comment by emoen** [comment]
Jeg skal undersøke om det er mulig å bytte ut lagre med lagre-nytt sånn at det ikke er mulig å overskrive et kartlag.

**Comment by emoen** [comment]
Har lagt ut denne fixen på mareano.no
