### ISSUE TITLE
7. Mapper forsvinner når en slår kartlag av/på.

### ISSUE THREAD

**Issue by kjellb** [Norwegian-marine-datacentre/mareano#147]
Markering av mapper forsvinner når en slår kartlag av/på – vanskelig å finne tilbake når en velger andre mapper og lukker den som en var inne på (Jmfr. web-referat 11/6-14 Lilja).

**Comment by emoen** [comment]
4) undersøke om det er mulig å vise en x for kartbilder som har kartbilder slått på. Så kan man trykke en gang og få 'v' ikonet for å slå på alle kartlag under kartbilde
5) ha en knapp øverst i menyen som ekspanderer alle kartbilder som har påslått kartlag.

**Comment by kjellb** [comment]
Se på mulighet for å bruke 'utgrået' v for kun ett eller flere kartlag og vanlig 'v' for alle kartlag valgt. Hvis 'v' er utgrået og man trykker på den så skal man slå på alle kartlag i kartblidet.

**Comment by emoen** [comment]
En implementasjon av GeoExt.tree.TristateCheckboxNode er tatt med i http://trac.geoext.org/ticket/22 men er ikke sjekket inn i GeoExt.

**Comment by emoen** [comment]
Jeg har lagt på bold tekst viss et kartlag i en gruppe er slått på som @beateh foreslå ref #95
