### ISSUE TITLE
6 Bruk av målestokksvelgeren fører til lukking av kartvinduet

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#148]
Skjer i IE, men ikke i Firefoks eller Chrome. Hvis man velger en målestokk i nedtrekksmenyen, vil kursoren blinke bak målestokkstall, som feilaktig indikerer at det er mulig å slette tallet med backspace og skrive inn nytt nummer. Isteden fører bksp tilbake til forrige vindu (som ser ut til å være en standardfunksjon for browsere). Hvis man da trykker bksp raskt flare ganger, som man oftest gjør når man sletter noe, får man inntrykk av at kartet kræsjer. 
Enkleste løsningen kan være å ikke la kursoren blinke i målestokksvinduet.
![malestokk](https://cloud.githubusercontent.com/assets/5802537/4201917/9b00c2d8-3823-11e4-8ffd-ec589e8bcd66.PNG)

**Comment by emoen** [comment]
Forslag om å fjerne målestokk fra kartklienten fordi det vil variere med oppløsning av skjermen.

**Comment by aavelepland** [comment]
Jeg er enig.
Det kom også et tips på møtet i MD om å bruke ord istedenfor tall på zoom-bar, som sier noe om hvor mye inn eller ut man skal zoome/har zoomet (lokalt, regionalt, oversikt e.l.). Det er 18 zoom-nivåer, så det skal litt kreativitet til.

**Comment by emoen** [comment]
Fjernet målestokk vindu og lagt til scaleLine istedet, men har ikke klart å legge til tekst som sier noe om regional eller lokal på zoom baren. Der står kun zoomnivå 1 til 18.
