### ISSUE TITLE
større bilder

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#160]
Er bildene på kartene litt små? Sjekker mulighet til å legge inn større bilder/ev bedre forklaring på bildene om hvordan få de større. Størrelsen er stor nok, men legger til info under bildet om "klikk for stort bilde"/"Click to enlarge".

Se også på om det er mulig å få opp bildet nærmere bildepunktet.

Er det mulig å åpne flere bilder samtidig uten å lukke bilder?

Fra referat 15. oktober.

**Comment by TerryHannant** [comment]
Can now resize images by dragging window edge or resize icon. The resize does not allow resize above the image size to avoid stretching/distortion 

Can now open multiple images at same time.
