### ISSUE TITLE
MIssing pop-up med Layer title

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#168]
Layer title (long name) is not shown at mouse over. Used to be shown as pop-up in old Mareano-maps. This also applies to Kartbilde title (2. level folder in map TOC) and Hovedtema title (main level folders in TOC). Is this function planned as a part of functionality in new map application?

**Comment by emoen** [comment]
Is this needed for kartbilde and hovedtema? You can see the name in the layer tree.
