### ISSUE TITLE
6. Forby new line og space

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#173]
Kan man forby new line i tekstboksene? F.eks Generic Title, Keywords, layers. Og forby space i layers feltet. Viss det er new line eller space så får man problemer med å generere javascript. 

F.eks gir dette feil pga new line for Generic Title, Keywords, og layers feltene:
<pre>
 OLRecord = gxp.plugins.OLSource.prototype.createLayerRecord({
                    source: "ol",
                    type: "OpenLayers.Layer.WMS",
                    group: "alt",
                    queryable: false,
                    visibility: false,
                    properties: "mareano_wmslayerpanel",            
                    args: [
                        "havbunnraster_graatone_geonorge
",
                        "http://wms.geonorge.no/skwms1/wms.havbunnraster2",
                        {layers: "havbunnraster_graatone
", format: "image/png", transparent: true},
                        {
                            opacity: 1,
                            metadata: {
                                keyword: "havbunnraster_graatone
",
                                'kartlagId': '520'
                            },
                            minScale: 1.0E30*(96/0.0254),
                            maxScale: (0.0 > 0) ? 0.0*(96/0.0254) : 0.001,
                            units: "m",
                            maxExtent: [
                                0.0,
                                0.0,
                                0.0,
                                0.0
                            ],
                            singleTile:true,
                            buffer: 0, //getting no boarder around image - so panning will get a new image.
                            ratio: 1 //http://dev.openlayers.org/releases/OpenLayers-2.12/doc/apidocs/files/OpenLayers/Layer/Grid-js.html#OpenLayers.Layer.Grid.ratio                                        
                        }
                    ]
                });
</pre>

**Comment by aangerman** [comment]
I title og keywords blir linjeskift endret til space. I layers blir alle whitespaces fjernet.
