### ISSUE TITLE
Feil i header for visning av Kartlag.

### ISSUE THREAD

**Issue by kjellb** [Norwegian-marine-datacentre/mareano#174]
Kolonnenavn for BBOX north og BBOX south har byttet plass i listen over kartlag for kartbilder (view kartlag under kartbilder).
![kolonnenavn](https://cloud.githubusercontent.com/assets/5709725/10906888/7afb8412-8225-11e5-8605-a543c15cf3f9.png)

**Comment by aangerman** [comment]
Endret på testserver

**Comment by aangerman** [comment]
Kolonnenavn for BBOX north og BBOX south er flyttet til riktig plass.
