### ISSUE TITLE
Testbasen. Karttjeneste-URL i Info-boks/Abstrakt.

### ISSUE THREAD

**Issue by kjellb** [Norwegian-marine-datacentre/mareano#176]
Dersom man ønsker karttjeneste-URLen i info boksen, så er det mulig å lage et script som legger til URLen fra Kartlag/Karttjenester til Abstrakt i Norsk og Engelsk tekst.
Sjekk med NGU og Kartverket om de ønsnker det.

**Comment by emoen** [comment]
https://github.com/Norwegian-marine-datacentre/mareano/commit/3ea653c45049469c3e6ccdcfc858c723c576896d
