### ISSUE TITLE
Lagrede kart viser dobbel tegnforklaring, hvis åpnet gjennom lenken

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#178]
eks. http://www.mareano.no/kart/mareano.html#maps/1173
Begge tegnforklaringer forsvinner, når kartlaget blir slått av.

MAREANO-stasjoner som er med i et lagret kart som blindpassasjerere (se issue #177), får tredobbelt tegnforklaring. En av dem blir igjen, når alle tre lag av MAREANO-stasjoner blir slått av.

**Comment by emoen** [comment]
Denne oppgaven skal være løst for nye kartlag som man lagrer med fixen i #177. Men for eksiterende lagrete kartlag kan man fortsatt få double tegnforklaringer.
