### ISSUE TITLE
Generic title forsvinner ved første registrering av kartlag

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#181]
Generic title forsvinner ved første registrering av kartlag. På lista over kartlag (både i /Kartlag/index og /karttjenestes/view/#nn "Kartlag"   er feltet 'Generic title' tomt. Må gå inn gjennom "Edit kartlag" og legge inn 'Generic title' på nytt.

**Comment by aangerman** [comment]
Fikset på test-server.
