### ISSUE TITLE
"Kartbilder" blir ikke registrert ved førstegangsregistrering av et kartlag

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#182]
Når man setter opp et nytt kartlag i mareano_admin, og blant annet registrerer et kartbilde, der laget skal vises, blir denne informasjon ikke med ved lagring. Må gå inn på nytt gjennom "Edit kartlag" og legge til Kartbilder og lagre på nytt.

**Comment by aangerman** [comment]
Når man nå oppretter kartlag blir også kartbildene lagret.
