### ISSUE TITLE
Polar P overlays bør endrast til kartlag

### ISSUE THREAD

**Issue by PAH1** [Norwegian-marine-datacentre/mareano#201]
Polar P overlays bør endrast til kartlag

![image](https://user-images.githubusercontent.com/5708044/30580058-86eafe66-9d1b-11e7-8b46-6524d7773d13.png)

**Comment by emoen** [comment]
fikset i test

**Comment by emoen** [comment]
https://github.com/Norwegian-marine-datacentre/mareano/commit/69d0043257b7e957644e91b6d82010689857282a
