### ISSUE TITLE
Kartverket ikon ved stedsnavn Sjø og Polar vises ikkje

### ISSUE THREAD

**Issue by PAH1** [Norwegian-marine-datacentre/mareano#203]
Kartverket ikon ved stedsnavn Sjø og Polar vises ikkje:
![image](https://user-images.githubusercontent.com/5708044/33117437-c19d2866-cf68-11e7-8ed3-600b91d211c8.png)

**Comment by emoen** [comment]
Tjenesten som ikke får rett ikon er: openwms.statkart.no. Dette skal være fikset i test.

**Comment by PAH1** [comment]
virkar i test
