### ISSUE TITLE
Fremhev bakgrunnsfarge MarBunn

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#209]
Utvid også tooltip teksten. "gå til artslista - Marbunn"

**Comment by emoen** [comment]
Har lagt dette til i test:
![image](https://user-images.githubusercontent.com/1202040/46004377-0035b980-c0b3-11e8-919c-cc7577ef7409.png)

**Comment by kjellb** [comment]
Bakgrunnsfarge er hvit og viser tooltip tekst. OK.
