### ISSUE TITLE
legg til skjerm-tips for abstract på bilde og hovedtema nivå

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#210]
Test med kjemisk analyse > tungmetaller

**Comment by emoen** [comment]
Lagt til qtip for hovedtema og kartbilder i test.
![image](https://user-images.githubusercontent.com/1202040/46002538-a501c800-c0ae-11e8-9917-73c895f32edd.png)

**Comment by kjellb** [comment]
Er OK i produksjon. Testet av Kjell og Endre.
