### ISSUE TITLE
Dato

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#213]
display "Dato" from NGU togeter with data_shape from IMR

**Comment by aavelepland** [comment]
The enchancement is working well in test. There is a solution for both single layers end multiple layers-call. The issue of updating the WFS-call is discussed and approved. If there isn't any other concerns, the enchancement can be implemented on main Mareano-maps.
NB! We must remember that Dato shows the creation date of the newest feature in a data set, not the latest update of the data.

**Comment by kjellb** [comment]
Saken er lukket.
