### ISSUE TITLE
GetCapabilities call med versjon=1.1.1 fungerer ikke for nyere versjon av WMS

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#217]
GetCapabilities URL som er en del av Kartlag Egenskaper på MAREANO kart, inkluderer VERSJON=1.1.1. Denne versjonen er ikke gyldig for WMS tjenester som er tilgjengelige i nyere versjon (1.3.0)  Dette resulterer med at GetCapabilities call feiler.

_The major differences between versions 1.1.1 and 1.3.0 are:
•	In 1.1.1 geographic coordinate systems specified with the EPSG namespace are defined to have an axis ordering of longitude/latitude. In 1.3.0 the ordering is latitude/longitude. See Axis Ordering below for more details.
•	In the GetMap operation the srs parameter is called crs in 1.3.0. 
•	In the GetFeatureInfo operation the x and y parameters are called i and j in 1.3.0. GeoServer supports both keys regardless of version, except when in CITE-compliance mode._

Hvis VERSJON ikke er definert i GetCapabilities-call, vil tjenesten returnere svar i den nyeste versjonen eller det som er definert i tjenesten som default.

I og med at MAREANO henter kartlag fra flere tjenestetilbydere, kan det være vanskelig å definere en versjon som passer alle. 
**Det foreslås derfor å droppe versjon i GetCapabilities URL i Kartlag Egenskaper.**
For eksempel: http://geo.ngu.no/mapserver/MarinNaturtyperWMS2?REQUEST=GetCapabilities&

**Comment by emoen** [comment]
GetCapabilities URL uten version er lagt ut i test.

**Comment by kjellb** [comment]
Oppgaven er løst og lagt inn i produksjon. Testet av Aave, Kjell og Endre.
