### ISSUE TITLE
5. Ny Polar projeksjon -

### ISSUE THREAD

**Issue by PAH1** [Norwegian-marine-datacentre/mareano#73]
Ny mulighet til å velge polar projeksjon - som i AMSA kartene.
Det løyser problemene med kart som blir forvridd  ved Novaja Semlja /utkanten av UTM sona. Gebco / andre  kart. 
Det gir også eit bedre perspektiv på barentshavet og nordområdene.

**Comment by kjellb** [comment]
test version: http://webtest1.nodc.no/mareano/mareanoPolar.html

**Comment by emoen** [comment]
done
