### ISSUE TITLE
Oppdater metadata i Info om Kartlag

### ISSUE THREAD

**Issue by emoen** [Norwegian-marine-datacentre/mareano#90]
Se på lenker i metadata som finnes i den nye kartklienten under Info om Kartlag - her er lenker gamle (f.eks lenker man til havforskningsrapporten 2007) eller lenker mangler. Dette kan man se eksempler på under artsmangfold. Under f.eks blålang, bromse og flere arter.

**Comment by PAH1** [comment]
oppdatert
