### ISSUE TITLE
Skrollbar til Feature Info pop-up-vindu på kart

### ISSUE THREAD

**Issue by aavelepland** [Norwegian-marine-datacentre/mareano#99]
Det bør være en skrollbar nederst på pop-upvinduet til Feature Info. Alle lag i f.eks. Bestandsutbredelse har kjempebrede infotabeller, og eneste måte å få se all info på, er å trekke ut vinduet.  I verste fall kan det skje at det ikke er nok bredde på skjermen til at hele tabellen skulle bli synlig.
Det er også vanskelig å se at det er flere kolonner/mer info skjult bak høyre kanten av vinduet.

**Comment by sagenimr** [comment]
Er fikset.
